
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 14:52:04 COT 2020
//----------------------------------------------------

package sintactico1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ti = 2;
  public static final int trf = 5;
  public static final int tf = 3;
  public static final int cad = 10;
  public static final int thi = 8;
  public static final int EOF = 0;
  public static final int thf = 9;
  public static final int error = 1;
  public static final int tdi = 6;
  public static final int tri = 4;
  public static final int tdf = 7;
}

