
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 15:07:00 COT 2020
//----------------------------------------------------

package sintactico1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int fin_i = 11;
  public static final int id = 5;
  public static final int xfor = 7;
  public static final int EOF = 0;
  public static final int pi = 2;
  public static final int num = 4;
  public static final int asignacion = 8;
  public static final int op = 6;
  public static final int error = 1;
  public static final int pd = 3;
  public static final int to = 9;
  public static final int endfor = 10;
}

