/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizador1;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author Sistemas2.0
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
        AbrirArchivo();

    }

     String ruta = "src\\analizador1\\fuente.txt";
     
    private void AbrirArchivo() {
        try {
            String cadena = "";
            FileReader f = new FileReader(ruta);
            BufferedReader b = new BufferedReader(f);
            cadena = b.readLine();
            while (cadena != null) {
                txtFuente.append(cadena + "\n");
                cadena = b.readLine();
            }
            b.close();
        } catch (Exception e) {
            txtResultados.setForeground(Color.red);
            txtResultados.setText(e.getMessage());
        }
    }

    private void Guardar() {
        try {
            
            FileWriter f = new FileWriter(ruta);
            BufferedWriter b = new BufferedWriter(f);
            b.write(txtFuente.getText());
            b.close();
            txtResultados.setForeground(Color.blue);
            txtResultados.setText("Archivo Guardado");
        } catch (Exception e) {
            txtResultados.setText(e.getMessage());
        }
    }

    private void Compilar() {
        try {
            
            String archivo = new File(ruta).getAbsolutePath();
            Lexer lex = new Lexer(new FileReader(archivo));
            lex.yylex(); // compilar 
            if (lex.errlex.isEmpty()) {
                txtResultados.setForeground(Color.blue);
                txtResultados.setText("Compilación Correcta");
                txtResultados.append(lex.ts.toString());
//                int c1 = 0, c2 = 0, c3=0, c4=0, i=0;
//                for (i=0;i<lex.ts.size();i++){
//                    Token x = lex.ts.get(i);
//                    if (x.contenido.equals("GTA")) c1++;
//                    if (x.contenido.equals("GTG")) c2++;
//                    if (x.contenido.equals("GTT")) c3++;
//                    if (x.contenido.equals("GTC")) c4++;
//                }
//                txtResultados.append("\nLa secuencia 1 (GTA) esta " +  c1 + " veces");
//                txtResultados.append("\nLa secuencia 2 (GTG) esta " +  c2 + " veces");
//                txtResultados.append("\nLa secuencia 3 (GTT) esta " +  c3 + " veces");
//                txtResultados.append("\nLa secuencia 4 (GTC) esta " +  c4 + " veces");
//                
            } else {
                txtResultados.setForeground(Color.red);
                txtResultados.setText("Compilación Inorrecta");
                txtResultados.append(lex.errlex);
            }
        } catch (Exception e) {
            txtResultados.setForeground(Color.red);
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        cmdNuevo = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFuente = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico ");

        jLabel1.setText("Analizador Léxico - Código fuente");

        jToolBar1.setRollover(true);

        cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizador1/Recursos/nuevo.png"))); // NOI18N
        cmdNuevo.setToolTipText("Nuevo");
        cmdNuevo.setFocusable(false);
        cmdNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdNuevo);

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizador1/Recursos/salvar.png"))); // NOI18N
        cmdGuardar.setToolTipText("Guardar");
        cmdGuardar.setFocusable(false);
        cmdGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdGuardar);

        cmdCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizador1/Recursos/boton-de-play.png"))); // NOI18N
        cmdCompilar.setToolTipText("Compilar");
        cmdCompilar.setFocusable(false);
        cmdCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCompilarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdCompilar);

        txtFuente.setColumns(20);
        txtFuente.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtFuente.setRows(5);
        jScrollPane1.setViewportView(txtFuente);

        jLabel2.setText("Resultados de compilación");

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane2.setViewportView(txtResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
       Guardar();
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCompilarActionPerformed
        Guardar();
        Compilar();
    }//GEN-LAST:event_cmdCompilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCompilar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtFuente;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
